import type { Metadata } from "next";
import { Jura, Comfortaa } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Button, ConfigProvider, Space } from 'antd';
import Script from "next/script";
const inter = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Script src="https://telegram.org/js/telegram-web-app.js"></Script>
      <body className={inter.className}> 
      <AntdRegistry>  <ConfigProvider
    theme={{
      token: {
        // Seed Token
        colorPrimary: '#37a700',
        borderRadius: 5,

        // Alias Token
        // colorBgContainer: '#f6ffed',
      },
    }}
  >
    
    {children}</ConfigProvider></AntdRegistry>
    </body>
    </html>
  );
}
